version: '3.4'

services:
  forzalistener:
    image: ${DOCKER_REGISTRY-}forzalistener
    build:
      context: .
      dockerfile: ForzaListener/Dockerfile
    ports:
      - 1024:1024/udp
    depends_on:
      - graphite

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
#      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    volumes:
      - data:/var/lib/grafana
      
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "3001:80"
#      - 2003-2004:2003-2004
#      - 2023-2024:2023-2024
#      - 8125:8125/udp
#      - 8126:8126
    environment:
#      MEMCACHE_HOST: "memcached:11211"
      CACHE_DURATION: 60
    volumes:
      - logs:/var/log
      - logrotate_etc:/etc/logrotate.d
      - nginx_etc:/etc/nginx
      - conf:/opt/graphite/conf
      - storage:/opt/graphite/storage
      - custom:/opt/graphite/webapp/graphite/functions/custom
      - statsd_etc:/opt/statsd/config
      - redis:/var/lib/redis
          
volumes:
  data:
  logs:
  logrotate_etc:
  nginx_etc:
  conf:
  storage:
  custom:
  statsd_etc:
  redis:
